#!/bin/bash

BMCHOST=192.168.110.232
OSHOST=192.168.110.2

. env.sh

#robot -L debug -v OPENBMC_HOST:$BMCHOST -v OPENBMC_USERNAME:ADMIN -v OPENBMC_PASSWORD:ADMIN -v OPENBMC_SSH_USERNAME:admin -v OPENBMC_SSH_PASSWORD:admin -v IPMI_PASSWORD:ADMIN -v OS_HOST:$OSHOST -v OS_USERNAME:root -v OS_PASSWORD:root -v OPENBMC_PROMPT="# "  server/test.robot
robot -L debug -v OPENBMC_HOST:$BMCHOST -v OPENBMC_USERNAME:ADMIN -v OPENBMC_PASSWORD:ADMIN -v OPENBMC_SSH_USERNAME:root -v OPENBMC_SSH_PASSWORD:root -v IPMI_PASSWORD:ADMIN -v OS_HOST:$OSHOST -v OS_USERNAME:root -v OS_PASSWORD:root -v OPENBMC_PROMPT:"# "  server/test.robot
# robot -L debug server/test.robot




# robot -v IPMI_COMMAND:Inband -v OPENBMC_HOST:192.168.1.97 -v OPENBMC_USERNAME:ADMIN -v OPENBMC_PASSWORD:ADMIN -v IPMI_PASSWOR:ADMIN -v OS_HOST:192.168.1.75 -v OS_USERNAME:root -v OS_PASSWORD:root templates/test.robot
#robot -v OPENBMC_HOST:192.168.1.97 -v OPENBMC_USERNAME:admin -v OPENBMC_PASSWORD:admin -v OS_HOST:192.168.1.75 -v OS_USERNAME:root -v OS_PASSWORD:root templates/test.robot
